use actix_session::Session;
use actix_web::{http::header, web, HttpResponse};
use askama::Template;
use serde::Deserialize;
use sqlx::PgPool;
use validator::Validate;
use crate::{error::AppError, security};

#[derive(Template)] #[template(path="home.html")] struct HomeTemplate;
#[derive(Template)] #[template(path="page.html")] struct PageTemplate<'a>{title:&'a str,description:&'a str,canonical:&'a str,eyebrow:&'a str,heading:&'a str,intro:&'a str,items:&'a [PageItem<'a>]}
struct PageItem<'a>{title:&'a str,text:&'a str,detail:&'a str}
#[derive(Template)] #[template(path="contact.html")] struct ContactTemplate<'a>{csrf:&'a str,success:bool}

fn html<T:Template>(t:T)->Result<HttpResponse,AppError>{Ok(HttpResponse::Ok().content_type("text/html; charset=utf-8").insert_header((header::CACHE_CONTROL,"public, max-age=0, must-revalidate")).body(t.render()?))}
pub fn routes(cfg:&mut web::ServiceConfig){cfg.route("/",web::get().to(home)).route("/services",web::get().to(services)).route("/work",web::get().to(work)).route("/about",web::get().to(about)).route("/insights",web::get().to(insights)).route("/contact",web::get().to(contact)).route("/contact",web::post().to(submit_contact)).route("/robots.txt",web::get().to(robots)).route("/sitemap.xml",web::get().to(sitemap)).route("/health/live",web::get().to(live)).route("/health/ready",web::get().to(ready));}
async fn home()->Result<HttpResponse,AppError>{html(HomeTemplate)}
async fn services()->Result<HttpResponse,AppError>{let i=[PageItem{title:"Website development",text:"High-performance, responsive and SEO-ready websites that turn visitors into enquiries.",detail:"Actix · Askama · Core Web Vitals"},PageItem{title:"Web applications",text:"Secure portals, dashboards and SaaS products designed around real operations.",detail:"Rust · PostgreSQL · APIs"},PageItem{title:"Custom software",text:"Purpose-built systems and automations that remove repetitive work.",detail:"Automation · Integrations · AI"}];html(PageTemplate{title:"Web, App & Software Development Services | Italy Developers",description:"Secure Rust web development, applications and custom software.",canonical:"/services",eyebrow:"Digital product services",heading:"Engineering for ambitious businesses.",intro:"Strategy, design and secure Rust engineering brought together by one focused team.",items:&i})}
async fn work()->Result<HttpResponse,AppError>{let i=[PageItem{title:"Casa Viva",text:"Hospitality platform designed to increase direct reservations.",detail:"+38% direct bookings"},PageItem{title:"Linea",text:"Operations software replacing fragmented manual reporting.",detail:"12 hours saved weekly"},PageItem{title:"Forma",text:"A faster mobile commerce experience.",detail:"2.4× conversion"}];html(PageTemplate{title:"Rust Web Development Portfolio | Italy Developers",description:"Selected secure web and software outcomes.",canonical:"/work",eyebrow:"Selected work",heading:"Digital products measured by outcomes.",intro:"Distinctive design, dependable engineering and a clear business result.",items:&i})}
async fn about()->Result<HttpResponse,AppError>{let i=[PageItem{title:"Direct",text:"Work with the people thinking, designing and building.",detail:"No account layers"},PageItem{title:"Practical",text:"Every choice connects to users, operations and measurable goals.",detail:"Outcome led"},PageItem{title:"Secure",text:"Threat modelling and safe defaults are part of the architecture.",detail:"Security by design"}];html(PageTemplate{title:"About Our Rust Development Studio | Italy Developers",description:"An independent security-focused Rust product studio.",canonical:"/about",eyebrow:"About Italy Developers",heading:"Small team. Serious craft.",intro:"We build secure digital products for organisations in India, Italy and worldwide.",items:&i})}
async fn insights()->Result<HttpResponse,AppError>{let i=[PageItem{title:"Security belongs in product design",text:"Authentication, authorization, data boundaries and abuse cases should be designed before implementation.",detail:"Security"},PageItem{title:"When Rust creates leverage",text:"Rust is a strong choice for reliable APIs, predictable performance and memory safety.",detail:"Engineering"},PageItem{title:"SEO foundations that ship",text:"Semantic HTML, crawlable routes, metadata, useful content and fast pages are product requirements.",detail:"SEO"}];html(PageTemplate{title:"Rust, Security & Product Insights | Italy Developers",description:"Practical Rust, website security and product development articles.",canonical:"/insights",eyebrow:"Studio insights",heading:"Useful thinking for digital teams.",intro:"Practical notes for teams making software and security decisions.",items:&i})}
async fn contact(session:Session)->Result<HttpResponse,AppError>{let token=session.get::<String>("csrf").map_err(|_|AppError::BadRequest)?.unwrap_or_else(||format!("{:x}{:x}",std::process::id(),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_nanos()));session.insert("csrf",&token).map_err(|_|AppError::BadRequest)?;html(ContactTemplate{csrf:&token,success:false})}

#[derive(Deserialize,Validate)] struct ContactForm { #[validate(length(min=2,max=80))] name:String, #[validate(email,length(max=254))] email:String, #[validate(length(max=120))] company:Option<String>, #[validate(length(max=80))] service:Option<String>, #[validate(length(min=10,max=4000))] message:String, #[validate(length(max=0))] website:Option<String>, csrf:String }
async fn submit_contact(session:Session,pool:web::Data<PgPool>,form:web::Form<ContactForm>)->Result<HttpResponse,AppError>{form.validate().map_err(|_|AppError::BadRequest)?;let expected=session.get::<String>("csrf").map_err(|_|AppError::Forbidden)?.ok_or(AppError::Forbidden)?;if !security::csrf_valid(&expected,&form.csrf){return Err(AppError::Forbidden)} sqlx::query("INSERT INTO leads (name,email,company,service,message) VALUES ($1,$2,$3,$4,$5)").bind(form.name.trim()).bind(form.email.trim().to_lowercase()).bind(form.company.as_deref().map(str::trim)).bind(form.service.as_deref()).bind(form.message.trim()).execute(pool.get_ref()).await?;session.remove("csrf");html(ContactTemplate{csrf:"",success:true})}
async fn live()->HttpResponse{HttpResponse::Ok().json(serde_json::json!({"status":"ok"}))}
async fn robots()->HttpResponse{HttpResponse::Ok().content_type("text/plain; charset=utf-8").body("User-agent: *\nAllow: /\nDisallow: /health/\nSitemap: https://italydevelopers.com/sitemap.xml\n")}
async fn sitemap()->HttpResponse{HttpResponse::Ok().content_type("application/xml; charset=utf-8").body("<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"><url><loc>https://italydevelopers.com/</loc><priority>1.0</priority></url><url><loc>https://italydevelopers.com/services</loc></url><url><loc>https://italydevelopers.com/work</loc></url><url><loc>https://italydevelopers.com/about</loc></url><url><loc>https://italydevelopers.com/insights</loc></url><url><loc>https://italydevelopers.com/contact</loc></url></urlset>")}
async fn ready(pool:web::Data<PgPool>)->HttpResponse{match sqlx::query_scalar::<_,i32>("SELECT 1").fetch_one(pool.get_ref()).await{Ok(_)=>HttpResponse::Ok().json(serde_json::json!({"status":"ready"})),Err(_)=>HttpResponse::ServiceUnavailable().json(serde_json::json!({"status":"unavailable"}))}}
